### ISSUE TITLE
Add options to configure svgo

### ISSUE THREAD

**Issue by ewolfe** [1000ch/vscode-svgo#2]
I would like to keep the `viewBox` attribute when I prettify my svg's. Would you accept a pull request that allowed users to configure the svgo settings?

Great extension by the way!

**Comment by dotiful** [comment]
@ewolfe In the last release, a bunch of settings were added to allow you to configure svgo. this is amazing.
Also, @1000ch maybe it's already in your plans, it would be great to be able to specify the path to the global config file to extend or replace default settings.
and for example, if there is a let's say `.svgo.yml` in the root of the workspace, then use it. 
so, settings will apply in order: from workspace config file if any, then from global if specified, and use extension settings as a fallback

**Comment by 1000ch** [comment]
Yes, I am planning to implement to configure SVGO by loading `.svgo.yml` in workspace.

**Comment by 1000ch** [comment]
Fixed by #5.
