### ISSUE TITLE
Version 2.0.1 is not disabling default plugins

### ISSUE THREAD

**Issue by imrahil** [1000ch/vscode-svgo#33]
Changes in commit https://github.com/1000ch/vscode-svgo/commit/0bad94ded36deb7be73e1d779e276d84b4212a81 simply ignore settings from VS Code that are "false" so it's not possible to disable any plugins...

Please use new configuration schema with "active" field:
```
{
   name: 'builtinPluginName',
   active: false
}
```

so no `filter` but `map` when using `extendDefaultPlugins`:
```
const plugins = extendDefaultPlugins(defaultPlugins.map(plugin => {
  return {
      name: plugin,
      active: svgoConfig.get<boolean>(plugin as string)
    }
}));
```

**Comment by 1000ch** [comment]
Fixed on 33de71e.
