### ISSUE TITLE
Remove data-name

### ISSUE THREAD

**Issue by PubliAlex** [1000ch/vscode-svgo#6]
Hello,

Really nice plugin.  A must have to clean all unwanted stuff in an SVG.

However, my program heavily use data-name attribute that I would like to clean. Do you think it's possible to add an option to remove data-name ?

Best regards,

Alex

**Comment by 1000ch** [comment]
This should be discussed on [svgo](https://github.com/svg/svgo) because this plugin provides only features provided by that tool.
