### ISSUE TITLE
Add to context menu

### ISSUE THREAD

**Issue by kanlukasz** [1000ch/vscode-svgo#8]
Hello,
I think it would be useful to add the features of your plugin to the context menu

![obraz](https://user-images.githubusercontent.com/30685349/77621382-a4b0ea00-6f3c-11ea-8fb5-6c26d8ed3a6c.png)

**Comment by 1000ch** [comment]
Introduced in [the newest version](https://github.com/1000ch/vscode-svgo/releases/tag/v1.6.0).
